blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/TeamCodeStream/codestream/issues/new?assignees=&labels=question&template=
    about: Please ask any questions here.